// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_boilerplate/test/features/home/domain/usecases/get_home_data_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i3;

import 'package:flutter_boilerplate_core/flutter_boilerplate_core.dart' as _i5;
import 'package:flutter_boilerplate_domain/feature_home/entities/home_entity.dart'
    as _i4;
import 'package:flutter_boilerplate_domain/feature_home/repositories/home_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [HomeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRepository extends _i1.Mock implements _i2.HomeRepository {
  MockHomeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<(_i4.HomeEntity?, _i5.AppFailure?)> getHomeData() =>
      (super.noSuchMethod(
            Invocation.method(#getHomeData, []),
            returnValue: _i3.Future<(_i4.HomeEntity?, _i5.AppFailure?)>.value((
              null,
              null,
            )),
          )
          as _i3.Future<(_i4.HomeEntity?, _i5.AppFailure?)>);

  @override
  _i3.Future<(_i4.HomeEntity?, _i5.AppFailure?)> getHomeDetail(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getHomeDetail, [id]),
            returnValue: _i3.Future<(_i4.HomeEntity?, _i5.AppFailure?)>.value((
              null,
              null,
            )),
          )
          as _i3.Future<(_i4.HomeEntity?, _i5.AppFailure?)>);

  @override
  _i3.Future<bool> hasCachedData() =>
      (super.noSuchMethod(
            Invocation.method(#hasCachedData, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<(void, _i5.AppFailure?)> clearCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearCache, []),
            returnValue: _i3.Future<(void, _i5.AppFailure?)>.value((
              null,
              null,
            )),
          )
          as _i3.Future<(void, _i5.AppFailure?)>);

  @override
  _i3.Stream<(_i4.HomeEntity?, _i5.AppFailure?)> watchHomeData() =>
      (super.noSuchMethod(
            Invocation.method(#watchHomeData, []),
            returnValue: _i3.Stream<(_i4.HomeEntity?, _i5.AppFailure?)>.empty(),
          )
          as _i3.Stream<(_i4.HomeEntity?, _i5.AppFailure?)>);
}
